definitions:
  CommonError:
    properties:
      message:
        description: |-
          Message of the error
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casaumidita/controllers
  CommonSuccess:
    properties:
      message:
        description: |-
          Message of the error
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casaumidita/controllers
  GetHumidities:
    properties:
      data:
        $ref: '#/definitions/Humidities'
      message:
        description: |-
          Message of the response
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casaumidita/controllers
  GetHumidity:
    properties:
      data:
        $ref: '#/definitions/Humidity'
      message:
        description: |-
          Message of the response
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casaumidita/controllers
  Humidities:
    items:
      $ref: '#/definitions/Humidity'
    type: array
    x-go-package: casaumidita/models
  Humidity:
    properties:
      data_inserimento:
        description: |-
          Timestamp of insert
          in: time
        format: date-time
        type: string
        x-go-name: DateInsert
      id:
        description: |-
          Id of rain value
          in: int64
        format: int64
        type: integer
        x-go-name: Id
      valore:
        description: |-
          Value of Humidity
          in: int
        format: float
        type: number
        x-go-name: Value
    type: object
    x-go-package: casaumidita/models
  ReqAddHumidity:
    properties:
      valore:
        description: |-
          Value of the Humidity
          in: int
        format: float
        type: number
        x-go-name: Value
    type: object
    x-go-package: casaumidita/models
info:
  title: 'Humidity Api:'
  version: 0.1.1
paths:
  /humidities:
    get:
      description: Get humidity list
      operationId: listhumidity
      responses:
        "200":
          description: GetHumidities
          schema:
            $ref: '#/definitions/GetHumidities'
        "401":
          description: CommonError
          schema:
            $ref: '#/definitions/CommonError'
      security:
      - apiKey:
        - '[]'
  /humidity:
    post:
      description: Create a new humidity value
      operationId: addHumidity
      responses:
        "200":
          description: GetHumidity
          schema:
            $ref: '#/definitions/GetHumidity'
        "401":
          description: CommonError
          schema:
            $ref: '#/definitions/CommonError'
      security:
      - apiKey:
        - '[]'
  /lasthour:
    get:
      description: Get list of last hour of humidity values .... or the last value
        inserted
      operationId: lastHour
      responses:
        "200":
          description: GetHumidities
          schema:
            $ref: '#/definitions/GetHumidities'
        "401":
          description: CommonError
          schema:
            $ref: '#/definitions/CommonError'
      security:
      - apiKey:
        - '[]'
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
